[filters]
public_key = true
public_key_filter_mode = "InvalidFilterMode"
kind = true
kind_filter_mode = "InvalidFilterMode"
word = false

[database]
host = "localhost"
port = "5432"
user = "chief"
password = "changeme"
dbname = "chief"
