datasource_mode = "Db"

[filters]
public_key = true
public_key_filter_mode = "Whitelist"
kind = true
kind_filter_mode = "Blacklist"
word = false

[filters.rate_limit]
enabled = true
max_events = 10
time_window = 60 # in seconds

[database]
host = "localhost"
port = "5432"
user = "chief"
password = "changeme"
dbname = "chief"

[json]
file_path = ""